application: pengeluaran-pemasukan
service: default
runtime: go
api_version: go1

handlers:
  - url: /create-resume
    script: _go_app
  - url: /createkursor
    script: _go_app
  - url: /stylesheets
    static_dir: styles
  - url: /scripts
    static_dir: scripts
  - url: /images
    static_dir: images
  - url: /templates
    static_dir: templates
    application_readable: true
  - url: /.*
    login: required
    script: _go_app
    secure: always
